### ISSUE TITLE
s/Huw/Hugh

### ISSUE THREAD

**Issue by jkingsman** [andrewholding/PlotArcs#1]
I LOVE the graph!! Definitely gonna be using it for some watch-throughs during SIP.

One tiny thing -- I believe the character's name is spelled [Hugh, not Huw](https://www.startrek.com/database_article/hugh) 🙂 

Just wanted to give you a heads up!

Thanks for some amazing work 😄

**Comment by andrewholding** [comment]
Thanks, I'll fix it in the next version.
